### ISSUE TITLE
[Clarification request] entropie vs. length of wordlist file

### ISSUE THREAD

**Issue by Wikinaut** [timoh6/GenPhrase#3]
I set up a wordlist file with 26 lines comprising the words (characters) "a" .. "z".

Each "word" contributes log2(26) = 4,7 bit okay ?

My program 
```
<?php
require 'library/GenPhrase/Loader.php';
$loader = new GenPhrase\Loader();
$loader->register();
$gen = new GenPhrase\Password();
# $gen->disableSeparators(false); // No separator characters are inserted

$gen->disableWordModifier(true); // No words are capitalized or changed to lower case (words are not modified)
$gen->setSeparators('--');
$gen->alwaysUseSeparators(true);
echo $gen->generate(52) . "\n";
```

Example output:
`h-x-m-p-j-h-q-c-u-u`

generates only 10 "words", which means ~ 47 bit entropy instead of the requested 52.

Pls. can you explain ?

**Comment by Wikinaut** [comment]
By the way, I do not see any reason to require "at least 20 different words" in the wordlist.

**Comment by timoh6** [comment]
This happens because you set two same separator characters. Two separator characters will give you 1 bit of entropy, but now as they are both "-" you won't get any extra entropy out of them (entropy is zero).

I'm thinking should this be made more clear in the documentation or even make GenPhrase reject setting duplicate separators. I'll start making the documentation more clear about setting separator characters. Thanks!

> By the way, I do not see any reason to require "at least 20 different words" in the wordlist.

This was just a "random limit", I didn't want to allow too short word pools as the resulting passphrases will be longer. With 2 words pool, you'd get 50+ passphrases which are unpractical to type and one could (easier) end up in situation where the resulting passphrase is longer than, say, the 72 character max limit of bcrypt.

I'm open to change the limit, but I'd want to hear a good reasoning for the change.

**Comment by timoh6** [comment]
Updated the README in master: https://github.com/timoh6/GenPhrase/commit/86855b1045d11fb01a508c32784251666e21f429

Does this look OK (as far as it comes to documentation)?

**Comment by Wikinaut** [comment]
* regarding "uniqueness", in my view, GenPhrase should make used Wordlist(s) and separators unique, before using.

* regarding the 20-limit: I wanted to use i) a wordlist of binary (two) items like "0", "1" or ii) of hex digits "0".."9", "A" .. "F".  Why not ? Then GenPhrase could easily generate passwords like BADCAFE7788 or 01010101010101110101111111101011111 - why not ?

* regarding separators: I will file a separate issue.

**Comment by timoh6** [comment]
In master it is now possible to use just two words as the word pool.

About the separator uniqueness issue (which is fixed in master now), I think you are eligible for a security bug bounty. If you are interested, I'll send you 10€ via PayPal (message me your email address and we can arrange the details). Thanks!

**Comment by Wikinaut** [comment]
No, you are entitled to receive some milliBitcoins from me for your swift changes and kind replies! Just place your receiving address here.

**Comment by timoh6** [comment]
I will be tagging v1.2 probably next week (from the current master). Please re-open this if you see fit.

Oh thanks, you can use the following address if you want to make a transfer:

1Pd75mwh4EB2mZzgbfiKY8HWBo9GuKRz1N

(I suggest make the smallest possible transfer, as I have never used Bitcoin before, just curious how it works).

**Comment by Wikinaut** [comment]
ok, I sent you very small test amount.

**Comment by timoh6** [comment]
Payment received, thanks alot!

**Comment by Wikinaut** [comment]
@timoh6 ready for more?

**Comment by timoh6** [comment]
The same address should be still working, or you can use this new one:

138pL17LxbLc1hDgJMCK6CLgBGuNbvqGbb

But I emphasize it was you who helped make Genphrase better, so the bitcoins was moving kind of wrong direction.

**Comment by Wikinaut** [comment]
but you coded it, published it here, and I simply found what I needed in two seconds (this repo). And you are kind enough to make some modifications. win-win-situation.


Transfer done. If you like, donate to other projects like Tails, Courage Foundation, Veracrypt, Enigmail, riseup....

**Comment by timoh6** [comment]
Thanks, will do!

If it is a problem for you to go with master, I'll try to tag v1.2 today.

**Comment by Wikinaut** [comment]
I'll go with master, no need for tagging.
